### PR TITLE
#54: Testimonial Widget in tech-solutiion

### PR DESCRIPTION
**Pull request by FroyoAndroid**
Please review @avi-stacksavings @stacksavings

### CODE REVIEW

**Comment by stacksavings** [comment]
Thanks, I was away on a trip and had no reception,. I will review tonight

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
@stacksavings to test on FTP do i need to just merge pull request?
I am sure what to do here.

**Comment by stacksavings** [comment]
He should not be using a pull request. He should be committing directly on master branch. Please get this sorted out.


⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
@stacksavings Okay got it.

**Comment by FroyoAndroid** [comment]
Approved and merged

**Comment by stacksavings** [comment]
Do not do this again, do not create new tickets for no reason

**Comment by avi-stacksavings** [comment]
@stacksavings this ticket got created coz he added Pull request.

@FroyoAndroid you can push directly from now on as i mentioned today. you can just show me on c9 .. if its working there. then you can push the changes without any pull request.
Please acknowledge if read this comment.

**Comment by FroyoAndroid** [comment]
@stacksavings @avi-stacksavings the template file from tech-solution folder has been removed.
no it uses the template file which is present in the widget section.
Please review the changes.

**Comment by avi-stacksavings** [comment]
@niraj you need to update in #54 not here.

**Comment by stacksavings** [comment]
Ok have Avi test then as soon as possible

⁣Sent from BlueMail ​

**Pull request merged**
